In [1]:
rand(3,2)

NameError: name 'rand' is not defined

In [2]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [4]:
import numpy as np

In [5]:
np.random.rand(5)

array([0.36905765, 0.88554364, 0.64365694, 0.01677159, 0.02053888])

In [6]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [7]:
np.random.rand(2,4)

array([[0.10702006, 0.25142655, 0.18882739, 0.18414695],
       [0.0127013 , 0.67201454, 0.16262477, 0.50442857]])

In [8]:
np.random.randint(2,4)

3

In [12]:
np.random.randint(2,20)  #secound argument is exlusive

13

In [13]:
np.random.randint(0,1)

0

In [15]:
np.random.randint(1,6,4)

array([2, 3, 2, 5])

In [16]:
np.random.rand(3)

array([0.71810595, 0.76306145, 0.29365506])

In [17]:
np.random.randint(1)

0

In [19]:
np.random.randint(10,20,30)

array([17, 12, 18, 17, 15, 12, 12, 13, 15, 17, 19, 18, 16, 15, 14, 10, 19,
       16, 16, 12, 13, 10, 13, 12, 11, 15, 13, 11, 15, 16])

In [20]:
np.random.randint(-30,20,10)

array([-20,  -3,  19,  -4, -17,   2, -13,  -1,   8,  14])

In [21]:
np.random.randint(20,30,10)  # 20 start 30 end 10 size 

array([23, 26, 21, 23, 24, 21, 22, 26, 25, 20])

In [22]:
np.random.randint(5,9) #it will genrate random number between 5 to 9

8

In [26]:
np.random.randint(10,21,3)

array([10, 17, 20])

In [27]:
np.random.randint(1,12,10)

array([ 7,  8, 11, 10,  3,  1, 11,  1,  1,  6])

In [28]:
np.random.randint(10,40,(10,10))

array([[17, 22, 33, 39, 34, 28, 25, 21, 23, 36],
       [24, 17, 15, 11, 25, 21, 36, 17, 27, 22],
       [12, 16, 12, 21, 20, 27, 25, 33, 30, 32],
       [33, 25, 20, 18, 23, 35, 39, 30, 19, 23],
       [13, 33, 17, 35, 13, 23, 39, 26, 17, 10],
       [32, 19, 32, 23, 33, 21, 12, 22, 24, 12],
       [20, 34, 29, 35, 37, 11, 28, 16, 28, 39],
       [19, 14, 39, 27, 14, 18, 36, 16, 33, 32],
       [16, 39, 24, 23, 34, 30, 31, 39, 22, 22],
       [28, 33, 38, 16, 24, 30, 20, 17, 25, 10]])

In [29]:
np.random.randint(1,100,(12,12)) #here the matrix is 12 * 12 and it genrates the vale between 1 to 99

array([[28, 74, 71, 70, 23, 63, 91, 67, 43,  5, 10, 43],
       [38, 26, 11,  6, 22, 56, 28, 89, 89,  5, 51, 66],
       [19, 14, 38, 73, 42, 43, 48, 96, 47,  6, 94, 81],
       [58, 76, 77, 36, 99, 28, 16, 47, 30, 93,  3, 52],
       [39, 83, 87, 95, 99, 20, 97,  4, 82,  8,  6, 67],
       [ 1, 52,  1, 67, 43,  9, 60, 78, 24, 35,  9, 47],
       [33, 38, 85, 98, 36, 90, 56, 77, 28, 49, 66, 65],
       [36, 98,  5, 56, 96, 51, 44, 48, 24,  3,  4, 40],
       [66,  9, 61, 95, 31, 72, 73, 30, 37, 85, 91, 93],
       [95, 32, 47, 29, 98, 19, 72, 76, 24, 15, 20, 58],
       [90, 39, 25, 65, 84, 94,  8, 29, 25, 73, 21, 19],
       [88, 63, 40, 91, 19, 19, 29,  3, 19, 15, 55, 59]])

In [31]:
np.arange(1,13).reshape(3,4) #reshape means 3 rows and 4 columns nither it is look like list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [33]:
b= np.random.randint(10,20,(5,4))
b


array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [34]:
type(b)

numpy.ndarray

In [35]:
b

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [36]:
b[:]

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [37]:
b[1:3]

array([[19, 16, 12, 16],
       [18, 14, 18, 10]])

In [38]:
b

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [39]:
b[1:2]

array([[19, 16, 12, 16]])

In [40]:
b[1,2] #for specific element we use (,) comma

12

In [41]:
b[4,3]

11

In [42]:
b[2,2]

18

In [43]:
b

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [44]:
b[1,-1]

16

In [45]:
b

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [46]:
b[2:3]

array([[18, 14, 18, 10]])

In [47]:
b[0:-2]

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10]])

In [48]:
b[0,2]

10

In [49]:
b[-5,-3]

16

In [50]:
b[-4,2]

12

In [51]:
np.random.randint(10,20,(4,4))

array([[12, 11, 11, 12],
       [12, 15, 17, 19],
       [18, 13, 13, 19],
       [16, 17, 19, 16]])

In [52]:
b

array([[13, 16, 10, 11],
       [19, 16, 12, 16],
       [18, 14, 18, 10],
       [11, 18, 15, 16],
       [11, 11, 17, 11]])

In [53]:
b[-4,-2]

12

In [54]:
b[-4:2]

array([[19, 16, 12, 16]])

Operation

In [56]:
a = np.random.randint(10,20,10)
a

array([13, 14, 13, 11, 18, 12, 10, 14, 16, 19])

In [57]:
id(a)

1845430408496

In [60]:
arr2 = np.random.randint(0,100,(10,10))

In [61]:
arr2

array([[28, 83, 79, 58, 48, 78, 52, 66, 74, 18],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3],
       [42, 49, 19, 68, 48, 95, 65, 85, 33, 60],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [ 2, 71, 51, 15, 56, 67, 22, 98, 12, 97],
       [81, 85, 20, 93, 88, 36, 23, 31, 38, 96],
       [33, 74, 73, 26, 61, 75, 51, 70, 96, 97],
       [89, 31, 15, 34, 16, 35, 18, 13, 73, 54],
       [ 8, 74, 52, 27, 57, 24, 82, 78, 40, 27],
       [85, 36, 35, 24, 55, 60, 53, 63, 55, 52]])

In [62]:
arr =[0,1,2,3,4,5]

In [63]:
arr

[0, 1, 2, 3, 4, 5]

In [64]:
arr[:4]

[0, 1, 2, 3]

In [65]:
arr2[0:5]

array([[28, 83, 79, 58, 48, 78, 52, 66, 74, 18],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3],
       [42, 49, 19, 68, 48, 95, 65, 85, 33, 60],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [ 2, 71, 51, 15, 56, 67, 22, 98, 12, 97]])

In [66]:
arr2

array([[28, 83, 79, 58, 48, 78, 52, 66, 74, 18],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3],
       [42, 49, 19, 68, 48, 95, 65, 85, 33, 60],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [ 2, 71, 51, 15, 56, 67, 22, 98, 12, 97],
       [81, 85, 20, 93, 88, 36, 23, 31, 38, 96],
       [33, 74, 73, 26, 61, 75, 51, 70, 96, 97],
       [89, 31, 15, 34, 16, 35, 18, 13, 73, 54],
       [ 8, 74, 52, 27, 57, 24, 82, 78, 40, 27],
       [85, 36, 35, 24, 55, 60, 53, 63, 55, 52]])

In [67]:
arr2[1,4]

80

In [68]:
arr2[-5,5]

36

In [69]:
arr2[-5,-5]

36

In [70]:
arr2 [-1,-2]

55

In [71]:
arr2[::-1]

array([[85, 36, 35, 24, 55, 60, 53, 63, 55, 52],
       [ 8, 74, 52, 27, 57, 24, 82, 78, 40, 27],
       [89, 31, 15, 34, 16, 35, 18, 13, 73, 54],
       [33, 74, 73, 26, 61, 75, 51, 70, 96, 97],
       [81, 85, 20, 93, 88, 36, 23, 31, 38, 96],
       [ 2, 71, 51, 15, 56, 67, 22, 98, 12, 97],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [42, 49, 19, 68, 48, 95, 65, 85, 33, 60],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3],
       [28, 83, 79, 58, 48, 78, 52, 66, 74, 18]])

In [72]:
arr2

array([[28, 83, 79, 58, 48, 78, 52, 66, 74, 18],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3],
       [42, 49, 19, 68, 48, 95, 65, 85, 33, 60],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [ 2, 71, 51, 15, 56, 67, 22, 98, 12, 97],
       [81, 85, 20, 93, 88, 36, 23, 31, 38, 96],
       [33, 74, 73, 26, 61, 75, 51, 70, 96, 97],
       [89, 31, 15, 34, 16, 35, 18, 13, 73, 54],
       [ 8, 74, 52, 27, 57, 24, 82, 78, 40, 27],
       [85, 36, 35, 24, 55, 60, 53, 63, 55, 52]])

In [73]:
arr2[::-2]

array([[85, 36, 35, 24, 55, 60, 53, 63, 55, 52],
       [89, 31, 15, 34, 16, 35, 18, 13, 73, 54],
       [81, 85, 20, 93, 88, 36, 23, 31, 38, 96],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [25,  7,  0,  6, 80, 71, 43,  8, 56,  3]])

In [74]:
arr2[::-3]

array([[85, 36, 35, 24, 55, 60, 53, 63, 55, 52],
       [33, 74, 73, 26, 61, 75, 51, 70, 96, 97],
       [40, 21, 46, 85, 46, 62, 23, 43, 16, 85],
       [28, 83, 79, 58, 48, 78, 52, 66, 74, 18]])